sudo: false

language: c

notifications:
  email:
    recipients:
      - ondra@nekola.cz

addons:
  apt:
    packages:
    - libgmp-dev

# The different configurations we want to test. You could also do things like
# change flags or use --stack-yaml to point to a different file.
env:
- ARGS=""
- ARGS="--resolver lts-3"
- ARGS="--resolver lts-7"
- ARGS="--resolver lts"

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'


# This line does all of the work: installs GHC if necessary, build the library,
# executables, and test suites, and runs the test suites. --no-terminal works
# around some quirks in Travis's terminal implementation.
script: |
    cd Simulation/Lib ;
    stack $ARGS install alex --no-terminal ;
    stack $ARGS install happy --no-terminal ;
    stack $ARGS install cabal-install --no-terminal ;
    stack $ARGS --no-terminal --install-ghc install gtk2hs-buildtools --haddock ;
    stack $ARGS setup --upgrade-cabal --install-ghc --no-terminal ;
    stack $ARGS solver --update-config --no-terminal ;
    stack $ARGS --no-terminal --install-ghc test --haddock

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

