language: haskell
notifications:
  email:
    recipients:
      - ondra@nekola.cz
ghc: 7.8
install:
  - cabal install FrozenBeagle
script:
  - cabal configure --enable-tests && cabal build FrozenBeagle && cabal test